
const $ = s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
const LS={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const KEYS={settings:'dp_settings',products:'dp_products',sales:'dp_sales',clients:'dp_clients',invmov:'dp_invmov',cash:'dp_cash',zmark:'dp_zmark'};
function uid(){return 'S'+Math.random().toString(36).slice(2,10)+Date.now().toString(36)}
const DEFAULT_SETTINGS={businessName:"DINAMITA GYM",address:"",phone:"",footer:"Gracias por tu compra 💥",logo:null,taxRate:0,currency:"MXN",ticketWidth58mm:true,paymentMethods:["Efectivo"],folioPrefix:"DG-2025-",nextFolio:1,whatsappPhone:"",whatsappMsg:"",showWhatsQR:false};
const CATEGORIES=["Suplementos","Accesorios","Membresías","Bebidas"];
const SAMPLE_PRODUCTS=[{id:uid(),sku:"PRO-001",name:"Proteína Whey 2lb",price:549,cost:380,category:"Suplementos",stock:8,image:null},{id:uid(),sku:"MEN-001",name:"Mensualidad (1 mes)",price:300,cost:0,category:"Membresías",stock:9999,image:null}];
function ensure(){ if(!LS.get(KEYS.settings)) LS.set(KEYS.settings,DEFAULT_SETTINGS); if(!LS.get(KEYS.products)) LS.set(KEYS.products,SAMPLE_PRODUCTS); if(!LS.get(KEYS.sales)) LS.set(KEYS.sales,[]); if(!LS.get(KEYS.clients)) LS.set(KEYS.clients,[]); if(!LS.get(KEYS.invmov)) LS.set(KEYS.invmov,[]); if(!LS.get(KEYS.cash)) LS.set(KEYS.cash,[]); if(!LS.get(KEYS.zmark)) LS.set(KEYS.zmark,null);} ensure();
const State={route:'ventas',cart:[]};
function format(n){ const s=LS.get(KEYS.settings,DEFAULT_SETTINGS); return n.toLocaleString('es-MX',{style:'currency',currency:s.currency||'MXN'}); }
function genFolio(){ const s=LS.get(KEYS.settings,DEFAULT_SETTINGS); const n=s.nextFolio||1; const f=s.folioPrefix+String(n).padStart(4,'0'); s.nextFolio=n+1; LS.set(KEYS.settings,s); return f; }
function nav(r){ State.route=r; $$(".nav button").forEach(b=>b.classList.toggle('active',b.dataset.route===r)); $$(".view").forEach(v=>v.style.display=(v.id===r?'block':'none')); if(r==='ventas') renderVentas(); if(r==='catalogo') renderCatalogo(); if(r==='inventario') renderInventario(); if(r==='clientes') renderClientes(); if(r==='historial') renderHistorial(); if(r==='config') renderConfig(); }
function add(p){ const it=State.cart.find(i=>i.id===p.id); if(it) it.qty++; else State.cart.push({id:p.id,name:p.name,price:p.price,qty:1}); drawCart(); }
function qty(id,q){ const it=State.cart.find(i=>i.id===id); if(!it)return; it.qty=Math.max(1,parseInt(q||1)); drawCart(); }
function rem(id){ State.cart=State.cart.filter(i=>i.id!==id); drawCart(); }
function totals(){ const s=LS.get(KEYS.settings,DEFAULT_SETTINGS); const sub=State.cart.reduce((a,b)=>a+b.price*b.qty,0); const tax=sub*(s.taxRate/100); return {subtotal:sub,tax,total:sub+tax}; }
function drawCart(){ const w=$("#cartLines"); w.innerHTML=""; State.cart.forEach(l=>{ const d=document.createElement('div'); d.className='line'; d.innerHTML=`<span>${l.name} x <input type="number" min="1" value="${l.qty}" onchange="qty('${l.id}',this.value)"/></span><b>${format(l.price*l.qty)}</b><button class="icon" onclick="rem('${l.id}')">🗑️</button>`; w.appendChild(d); }); const t=totals(); $("#subtotal").textContent=format(t.subtotal); $("#tax").textContent=format(t.tax); $("#total").textContent=format(t.total); $("#btnCobrar").disabled=State.cart.length===0; }
function renderVentas(){ const prods=LS.get(KEYS.products,[]); const q=$("#searchVenta").value?.toLowerCase()||""; const cat=$("#filterCatVenta").value||"all"; const grid=$("#ventaGrid"); grid.innerHTML=""; prods.filter(p=>(cat==='all'||p.category===cat)&&(p.name.toLowerCase().includes(q)||p.sku.toLowerCase().includes(q))).forEach(p=>{ const c=document.createElement('div'); c.className='card'; const img=p.image?`<img src="${p.image}"/>`:`<div style="height:140px;border-radius:10px;background:#141418;display:flex;align-items:center;justify-content:center">🛒</div>`; c.innerHTML=`${img}<h3>${p.name}</h3><div class="small">${p.sku} • ${p.category}</div><div class="row" style="align-items:center;justify-content:space-between;margin-top:6px"><b>${format(p.price)}</b><button class="btn" onclick='add(${JSON.stringify(p)})'>Agregar</button></div>`; grid.appendChild(c); }); drawCart(); }
function confirmarVenta(){ const t=totals(); const folio=genFolio(); const sale={id:folio,ts:new Date().toISOString(),items:JSON.parse(JSON.stringify(State.cart)),subtotal:t.subtotal,tax:t.tax,total:t.total,payments:[{method:"Efectivo",amount:t.total}],customerName:null}; const products=LS.get(KEYS.products,[]); sale.items.forEach(it=>{ const p=products.find(pp=>pp.id===it.id); if(p&&p.category!=="Membresías"){ p.stock=Math.max(0,(p.stock||0)-it.qty);} }); LS.set(KEYS.products,products); const sales=LS.get(KEYS.sales,[]); sales.unshift(sale); LS.set(KEYS.sales,sales); const cash=LS.get(KEYS.cash,[]); cash.unshift({id:uid(),ts:sale.ts,type:"Entrada",amount:sale.total,note:"Venta "+sale.id}); LS.set(KEYS.cash,cash); State.cart=[]; renderVentas(); renderHistorial(); printTicket(sale); }
function printTicket(sale){ const s=LS.get(KEYS.settings,DEFAULT_SETTINGS); const w=window.open("","PRINT","width=420,height=620"); const styles=document.querySelector('link[href="css/styles.css"]').outerHTML; const logo=s.logo?`<img src="${s.logo}" style="max-width:100px;display:block;margin:0 auto 6px auto" />`:`<div style="text-align:center;font-weight:900">${s.businessName.slice(0,1)}</div>`; let html=`<html><head>${styles}<title>Ticket</title></head><body><div class="ticket"><div class="center">${logo}</div><div class="center"><h1>${s.businessName}</h1><div class="muted">${s.address||""}</div><div class="muted">${s.phone||""}</div></div><hr/><div class="muted">Folio: <b>${sale.id}</b> • Fecha: ${new Date(sale.ts).toLocaleString('es-MX')}</div><table>`; sale.items.forEach(it=>{ html+=`<tr><td>${it.name} x ${it.qty}</td><td style="text-align:right">${format(it.price*it.qty)}</td></tr>`; }); html+=`</table><table class="totals"><tr><td>Subtotal</td><td style="text-align:right">${format(sale.subtotal)}</td></tr><tr><td>Impuestos</td><td style="text-align:right">${format(sale.tax)}</td></tr><tr><td><b>Total</b></td><td style="text-align:right"><b>${format(sale.total)}</b></td></tr></table><hr/><div class="muted">Pago: Efectivo ${format(sale.total)}</div><div class="center" style="margin-top:8px">${s.footer||""}</div></div><script>window.onload=()=>{ window.print(); setTimeout(()=>window.close(), 300); }</script></body></html>`; w.document.write(html); w.document.close(); }
function renderCatalogo(){ const prods=LS.get(KEYS.products,[]); const tbody=$("#catBody"); tbody.innerHTML=""; prods.forEach(p=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td>${p.sku}</td><td>${p.name}</td><td>${p.category}</td><td>${format(p.price)}</td><td>${p.stock??0}</td><td><button class="icon" onclick="editProduct('${p.id}')">✏️</button> <button class="icon" onclick="delProduct('${p.id}')">🗑️</button></td>`; tbody.appendChild(tr); }); $("#pCategory").innerHTML=CATEGORIES.map(c=>`<option>${c}</option>`).join(""); }
function clearProd(){ $("#pId").value=""; $("#pSku").value=""; $("#pName").value=""; $("#pPrice").value=""; $("#pCost").value=""; $("#pStock").value=""; $("#pImage").value=""; }
function saveProduct(){ const id=$("#pId").value||uid(); const sku=$("#pSku").value.trim(); const name=$("#pName").value.trim(); const price=parseFloat($("#pPrice").value||0); const cost=parseFloat($("#pCost").value||0); const category=$("#pCategory").value; const stock=parseInt($("#pStock").value||0); const prods=LS.get(KEYS.products,[]); const idx=prods.findIndex(p=>p.id===id); const upd=(img)=>{ const obj={id,sku,name,price,cost,category,stock,image:img}; if(idx>=0) prods[idx]=obj; else prods.unshift(obj); LS.set(KEYS.products,prods); clearProd(); renderCatalogo(); }; const f=$("#pImage").files[0]; if(f){ const r=new FileReader(); r.onload=e=>upd(e.target.result); r.readAsDataURL(f);} else { const prev=idx>=0?prods[idx].image:null; upd(prev);} }
function editProduct(id){ const p=LS.get(KEYS.products,[]).find(pp=>pp.id===id); if(!p)return; $("#pId").value=p.id; $("#pSku").value=p.sku; $("#pName").value=p.name; $("#pPrice").value=p.price; $("#pCost").value=p.cost; $("#pCategory").value=p.category; $("#pStock").value=p.stock??0; window.scrollTo({top:0,behavior:'smooth'}); }
function delProduct(id){ if(!confirm("¿Eliminar producto?")) return; const prods=LS.get(KEYS.products,[]).filter(p=>p.id!==id); LS.set(KEYS.products,prods); renderCatalogo(); }
function renderInventario(){ const prods=LS.get(KEYS.products,[]); const tbody=$("#invBody"); tbody.innerHTML=""; prods.forEach(p=>{ const low=(p.stock??0)<=2 && p.category!=="Membresías"; const tr=document.createElement('tr'); tr.innerHTML=`<td>${p.sku}</td><td>${p.name}</td><td>${p.category}</td><td>${p.stock??0} ${low?'<span class="badge" style="background:#f59e0b;color:#111">Bajo</span>':''}</td><td><div class="row"><input type="number" id="adj_${p.id}" placeholder="+/-"/><button class="btn secondary" onclick="adj('${p.id}')">Aplicar</button></div></td>`; tbody.appendChild(tr); }); }
function adj(id){ const prods=LS.get(KEYS.products,[]); const p=prods.find(pp=>pp.id===id); if(!p)return; const val=parseInt(($("#adj_"+id).value||"0"),10); if(!Number.isFinite(val)||val===0){ alert("Indica un ajuste"); return;} p.stock=Math.max(0,(p.stock||0)+val); LS.set(KEYS.products,prods); const inv=LS.get(KEYS.invmov,[]); inv.unshift({id:uid(),ts:new Date().toISOString(),prodId:id,delta:val}); LS.set(KEYS.invmov,inv); renderInventario(); }
function renderClientes(){ const list=LS.get(KEYS.clients,[]); const tbody=$("#cliBody"); tbody.innerHTML=""; const today=new Date().toISOString().slice(0,10); list.forEach(c=>{ const vig=c.vigencia||""; const badge=vig?(vig>=today?`<span style="background:#064e3b;color:#a7f3d0;padding:2px 8px;border-radius:999px;font-weight:800;font-size:12px">VIGENTE ${vig}</span>`:`<span style="background:#7f1d1d;color:#fecaca;padding:2px 8px;border-radius:999px;font-weight:800;font-size:12px">VENCIDO ${vig}</span>`):"—"; const tr=document.createElement('tr'); tr.innerHTML=`<td>${c.name}</td><td>${c.phone||""}</td><td>${c.email||""}</td><td>${badge}</td><td><button class="icon" onclick="editCliente('${c.id}')">✏️</button> <button class="icon" onclick="delCliente('${c.id}')">🗑️</button></td>`; tbody.appendChild(tr); }); }
function clearCliente(){ $("#cId").value=""; $("#cName").value=""; $("#cPhone").value=""; $("#cEmail").value=""; $("#cVig").value=""; }
function saveCliente(){ const id=$("#cId").value||uid(); const obj={id,name:$("#cName").value.trim(),phone:$("#cPhone").value.trim(),email:$("#cEmail").value.trim(),vigencia:$("#cVig").value||null}; const list=LS.get(KEYS.clients,[]); const idx=list.findIndex(x=>x.id===id); if(idx>=0) list[idx]=obj; else list.unshift(obj); LS.set(KEYS.clients,list); clearCliente(); renderClientes(); }
function editCliente(id){ const c=LS.get(KEYS.clients,[]).find(x=>x.id===id); if(!c)return; $("#cId").value=c.id; $("#cName").value=c.name; $("#cPhone").value=c.phone||""; $("#cEmail").value=c.email||""; $("#cVig").value=c.vigencia||""; window.scrollTo({top:0,behavior:'smooth'}); }
function delCliente(id){ if(!confirm("¿Eliminar cliente?")) return; const list=LS.get(KEYS.clients,[]).filter(c=>c.id!==id); LS.set(KEYS.clients,list); renderClientes(); }
function renderHistorial(){ const sales=LS.get(KEYS.sales,[]); const tbody=$("#hisBody"); tbody.innerHTML=""; sales.forEach(s=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td>${s.id}</td><td>${new Date(s.ts).toLocaleString('es-MX')}</td><td>${s.customerName||""}</td><td>${format(s.total)}</td><td><button class="icon" onclick='printTicket(${JSON.stringify(s)})'>🧾</button></td>`; tbody.appendChild(tr); }); const hoy=new Date().toISOString().slice(0,10); const totalHoy=sales.filter(s=>s.ts.slice(0,10)===hoy).reduce((a,b)=>a+b.total,0); $("#totalHoy").textContent=format(totalHoy); }
function renderConfig(){ const s=LS.get(KEYS.settings,DEFAULT_SETTINGS); $("#bName").value=s.businessName||""; $("#bAddr").value=s.address||""; $("#bPhone").value=s.phone||""; $("#bFooter").value=s.footer||""; $("#bTax").value=s.taxRate||0; $("#bCurrency").value=s.currency||"MXN"; $("#folioPrefix").value=s.folioPrefix||"DG-2025-"; $("#nextFolio").value=s.nextFolio||1; }
function saveConfig(){ const s=LS.get(KEYS.settings,DEFAULT_SETTINGS); s.businessName=$("#bName").value.trim(); s.address=$("#bAddr").value.trim(); s.phone=$("#bPhone").value.trim(); s.footer=$("#bFooter").value.trim(); s.taxRate=parseFloat($("#bTax").value||0); s.currency=$("#bCurrency").value||"MXN"; s.folioPrefix=$("#folioPrefix").value.trim()||"DG-2025-"; s.nextFolio=parseInt($("#nextFolio").value||1); LS.set(KEYS.settings,s); alert("Configuración guardada"); }
window.addEventListener('DOMContentLoaded',()=>{ $("#filterCatVenta").innerHTML=`<option value="all">Todo</option>`+CATEGORIES.map(c=>`<option value="${c}">${c}</option>`).join(""); renderVentas(); renderCatalogo(); renderInventario(); renderClientes(); renderHistorial(); renderConfig(); $$(".nav button").forEach(b=>b.addEventListener('click',()=>nav(b.dataset.route))); });
